"use client";

import { useParams } from "next/navigation";
import { useEstimateDetail, useCloneEstimate, useCreateEstimate, useDeleteEstimate } from "@/hooks/useEstimates";
import { useEngagement, useUpdateEngagement } from "@/hooks/useEngagements";
import { useRouter } from "next/navigation";
import { EstimateSpreadsheet } from "@/components/estimates/estimate-spreadsheet";
import { PhaseManagement } from "@/components/estimates/phase-management";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { useState, useEffect } from "react";

export default function EstimateDetailPage() {
  const params = useParams();
  const router = useRouter();
  const estimateId = params.id as string;
  const { data: estimate, isLoading, error } = useEstimateDetail(estimateId);
  const cloneEstimate = useCloneEstimate();
  const createEstimate = useCreateEstimate();
  const deleteEstimate = useDeleteEstimate();
  const [isCloning, setIsCloning] = useState(false);
  const [isCreating, setIsCreating] = useState(false);
  
  // Fetch engagement data for start/end dates and delivery center
  const { data: engagement } = useEngagement(estimate?.engagement_id || "", false);
  const updateEngagement = useUpdateEngagement();
  
  const [startDate, setStartDate] = useState<string>("");
  const [endDate, setEndDate] = useState<string>("");
  
  // Initialize dates from engagement
  useEffect(() => {
    if (engagement) {
      setStartDate(engagement.start_date || "");
      setEndDate(engagement.end_date || "");
    }
  }, [engagement]);

  const handleDuplicate = async () => {
    setIsCloning(true);
    try {
      const cloned = await cloneEstimate.mutateAsync({
        estimateId,
        newName: "", // Will be auto-generated by backend
      });
      // Redirect to the new estimate
      router.push(`/estimates/${cloned.id}`);
    } catch (err) {
      console.error("Failed to duplicate estimate:", err);
      alert(`Error: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setIsCloning(false);
    }
  };

  const handleNew = async () => {
    if (!estimate) return;
    
    setIsCreating(true);
    try {
      const newEstimate = await createEstimate.mutateAsync({
        engagement_id: estimate.engagement_id,
        name: "", // Will be auto-generated by backend as "VERSION [INCREMENT]"
      });
      // Redirect to the new estimate
      router.push(`/estimates/${newEstimate.id}`);
    } catch (err) {
      console.error("Failed to create estimate:", err);
      alert(`Error: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setIsCreating(false);
    }
  };

  const handleDelete = async () => {
    if (!estimate) return;
    
    if (!confirm(`Are you sure you want to delete estimate "${estimate.name}"?`)) {
      return;
    }
    
    try {
      await deleteEstimate.mutateAsync(estimate.id);
      // Redirect to estimates list
      router.push("/estimates");
    } catch (err) {
      console.error("Failed to delete estimate:", err);
      alert(`Error: ${err instanceof Error ? err.message : String(err)}`);
    }
  };

  const handleDateChange = async (field: "start_date" | "end_date", value: string) => {
    if (!estimate || !engagement) return;
    
    // Validation: start_date must be before end_date
    if (field === "start_date") {
      if (endDate && value && new Date(value) >= new Date(endDate)) {
        alert("Start date must be before end date");
        return;
      }
      setStartDate(value);
    } else {
      if (startDate && value && new Date(value) <= new Date(startDate)) {
        alert("End date must be after start date");
        return;
      }
      setEndDate(value);
    }
    
    // Update engagement
    try {
      await updateEngagement.mutateAsync({
        id: engagement.id,
        data: {
          [field]: value || undefined,
        },
      });
    } catch (err) {
      console.error(`Failed to update ${field}:`, err);
      alert(`Error: ${err instanceof Error ? err.message : String(err)}`);
      // Revert on error
      if (field === "start_date") {
        setStartDate(engagement.start_date || "");
      } else {
        setEndDate(engagement.end_date || "");
      }
    }
  };

  if (isLoading) {
    return (
      <div className="container mx-auto p-6">
        <Card>
          <CardContent className="p-6">
            <p>Loading estimate...</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (error || !estimate) {
    return (
      <div className="container mx-auto p-6">
        <Card>
          <CardContent className="p-6">
            <p className="text-red-600">
              {error
                ? `Error loading estimate: ${error instanceof Error ? error.message : String(error)}`
                : "Estimate not found"}
            </p>
            <Link href="/estimates">
              <Button className="mt-4">Back to Estimates</Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="w-full max-w-full overflow-x-hidden min-w-0">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6">
        <div>
          <Link href="/estimates" className="text-blue-600 hover:underline mb-2 inline-block">
            ← Back to Estimates
          </Link>
          <h1 className="text-3xl font-bold">{estimate.name}</h1>
          <p className="text-sm text-gray-500 mt-1">
            Engagement: {estimate.engagement_name || estimate.engagement_id}
            {estimate.opportunity_name && <> • Opportunity: {estimate.opportunity_name}</>}
          </p>
        </div>
        <div className="flex gap-2">
          {estimate.active_version ? (
            <span className="px-3 py-1 bg-green-100 text-green-800 rounded text-sm font-semibold flex items-center">
              ACTIVE VERSION
            </span>
          ) : (
            <span className="px-3 py-1 bg-gray-100 text-gray-800 rounded text-sm font-semibold flex items-center">
              PENDING VERSION
            </span>
          )}
          <Button onClick={handleNew} variant="outline" disabled={isCreating}>
            {isCreating ? "Creating..." : "NEW"}
          </Button>
          <Button onClick={handleDuplicate} variant="outline" disabled={isCloning}>
            {isCloning ? "Duplicating..." : "DUPLICATE"}
          </Button>
          {!estimate.active_version && (
            <Button 
              onClick={handleDelete} 
              variant="outline" 
              disabled={deleteEstimate.isPending}
              className="text-red-600 hover:text-red-700 hover:bg-red-50"
            >
              {deleteEstimate.isPending ? "Deleting..." : "DELETE"}
            </Button>
          )}
        </div>
      </div>

      <Card className="mb-6">
        <CardHeader>
          <CardTitle>Estimate Details</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
            {estimate.currency && (
              <div className="flex items-center">
                <span className="font-semibold mr-2">Currency:</span>
                <span>{estimate.currency}</span>
              </div>
            )}
            {engagement?.delivery_center_name && (
              <div className="flex items-center">
                <span className="font-semibold mr-2">Invoice Center:</span>
                <span>{engagement.delivery_center_name}</span>
              </div>
            )}
            {engagement?.default_currency && (
              <div className="flex items-center">
                <span className="font-semibold mr-2">Engagement Default Currency:</span>
                <span>{engagement.default_currency}</span>
              </div>
            )}
            <div>
              <label className="font-semibold block mb-1">Start Date:</label>
              <Input
                type="date"
                value={startDate}
                onChange={(e) => handleDateChange("start_date", e.target.value)}
                className="text-sm"
              />
            </div>
            <div>
              <label className="font-semibold block mb-1">End Date:</label>
              <Input
                type="date"
                value={endDate}
                onChange={(e) => handleDateChange("end_date", e.target.value)}
                className="text-sm"
              />
            </div>
            {estimate.description && (
              <div className="col-span-2">
                <span className="font-semibold">Description:</span> {estimate.description}
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      <PhaseManagement estimateId={estimate.id} />

      <EstimateSpreadsheet estimate={estimate} startDate={startDate} endDate={endDate} />
    </div>
  );
}

