.PHONY: up down restart logs clean

up:
	docker-compose up -d

down:
	docker-compose down

restart:
	docker-compose restart

logs:
	docker-compose logs -f

clean:
	docker-compose down -v
	docker system prune -f

build:
	docker-compose build

rebuild:
	docker-compose build --no-cache










